Repository zeppelinos/kernel, pull requests merged in 2018-04, with the labels that each got.

#5 Core contracts upgradeability
  contracts/KernelRegistry.sol
  contracts/KernelStakes.sol
  contracts/ZepCore.sol
  contracts/ZepToken.sol
  contracts/test/MockZepCoreV2.sol
  deploy/deployer.js
  helpers/decodeLogs.js
  package-lock.json
  package.json
  test/KernelController.test.js
  test/ZepCore.test.js
Labels: topic:upgradeability

#8 Improve deployment scripts
  README.md
  deploy/constants.js
  deploy/deployer.js
  deploy/logger.js
  deploy/objects/Deployer.js
  deploy/objects/ProjectControllerManager.js
  deploy/objects/RegistryManager.js
  deploy/objects/ZepCoreManager.js
  deploy/scripts/deploy.js
  deploy/scripts/initProject.js
  scripts/deploy.js
  scripts/initProject.js
  test/KernelController.test.js
  test/ZepCore.test.js
Labels: dev:help wanted, kind:chore, topic:tools

#6 Added requirement of KernelInstances to be registered before staking
  contracts/KernelRegistry.sol
  contracts/ZepCore.sol
  test/ZepCore.test.js
Labels: kind:tests

#9 Added coverage tests and TravisCI
  .gitignore
  .solcover.js
  .travis.yml
  README.md
  package-lock.json
  package.json
  scripts/test.sh
  truffle.js
Labels: kind:chore, kind:minor, kind:tests

#10 Move validations for registered instances to modifiers
  contracts/ZepCore.sol
Labels: kind:enhancement, topic:kernel

#13 Adds inline documentation for the contracts
  contracts/KernelInstance.sol
  contracts/KernelRegistry.sol
  contracts/KernelStakes.sol
  contracts/ZepCore.sol
Labels: kind:chore, topic:kernel

#11 Extends ZepCore staking tests
  test/ZepCore.test.js
  test/helpers/decodeLogs.js
Labels: kind:enhancement, kind:tests

#14 WIP Improvements to deploy scripts for ext. usage
  deploy/objects/Deployer.js
  deploy/objects/RegistryManager.js
  package.json
Labels: kind:chore, status:in progress, topic:tools

#20 Improve kernel instance test coverage
  contracts/ZepCore.sol
  contracts/ZepToken.sol
  test/KernelInstance.test.js
Labels: kind:tests, topic:kernel

#21 Add testing for instances from ZepCore
  test/ZepCore.test.js
Labels: kind:tests, topic:kernel

#29 Minor enhancements
  contracts/Kernel.sol
  contracts/Release.sol
  contracts/Vouching.sol
  contracts/test/Imports.sol
  package-lock.json
  package.json
  test/Release.test.js
Labels: kind:documentation, kind:enhancement, topic:kernel

#38 Update zos-cli to version 0.3.13
  package-lock.json
  package.json
Labels: status:review
